title: CC2020_Test_LearningPath1
description: >-
  Czieszymy się, że postanowiłeś do nas dołączyć w kolejnej edycji CodersCamp.
  Skoro otrzymałeś tę listę zadań, to znaczy, że udało Ci się pomyślnie przejść
  pierwszy etap rekrutacji i jesteś już o krok od dostania się na pełną wersję
  kursu.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
